# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Plugins
plugins:             [jekyll-paginate, jekyll-seo-tag]

# Setup
title:               alameenkhader.github.io
description:         ''
url:                 alameenkhader.github.io
tagline:             ''
baseurl:             ''
paginate:            20
paginate_path:       "page:num"

# About/contact
author:
  name:              Al Ameen
  url:               http://in.linkedin.com/in/al-ameen-khader-a8736452
  email:             alameenkhader@gmail.com

# Custom vars
version:             1.0.0
